### ISSUE TITLE
How to get basis coefficients?

### ISSUE THREAD

**Issue by juliohm** [baggepinnen/BasisFunctionExpansions.jl#4]
First off, thanks for this package!

Is there an API to retrieve basis coefficients and reconstruct approximation objects? I need to retrieve coefficients of approximation, do some calculations with them, generate new coefficients and reconstruct a signal with the updated coefficients using the same radial basis.

Please let me know how I can achieve this. If there is no exposed API yet, is it safe to lookup `bfa.linear_combinations`?

**Comment by baggepinnen** [comment]
Thanks for you interest!

It should be safe to access the linear combination directly. A gotcha might
be that the mu and sigma fields  are stored in the activation function as a
closure, changing these fields in the bfe object will not change the output
of the bfe, since they remain the same in the closure.

Sent from mobile device

On Sep 13, 2017 14:38, "Júlio Hoffimann" <notifications@github.com> wrote:

First off, thanks for this package!

Is there an API to retrieve basis coefficients and reconstruct
approximation objects? I need to retrieve coefficients of approximation, do
some calculations with them, generate new coefficients and reconstruct a
signal with the updated coefficients using the same radial basis.

Please let me know how I can achieve this. If there is no exposed API yet,
is it safe to lookup bfa.linear_combinations?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/baggepinnen/BasisFunctionExpansions.jl/issues/4>, or mute
the thread

**Comment by juliohm** [comment]
I appreciate if you can expose an API to reconstruct functions on the same basis. I tried to modify the linear combination explicitly yesterday, but apparently the reconstruction is not working as you explained.

My goal is to perform "Functional PCA", which is a fancy name for PCA on the coefficients of a basis expansion. Very often we need to reconstruct signals for new scores not seen in the training set.

**Comment by baggepinnen** [comment]
Is there any reason you can not create a new BasisFunctionApproximation with your new coefficients and old BasisFunctionExpansion like
`bfa_new = BasisFunctionApproximation(bfa_old.bfe, x_new)`?

**Comment by baggepinnen** [comment]
It is the parameters of the basis functions that are fixed and hard to modify, it is possible to modify the linear combination of these basis functions and have the reconstruction updated accordingly.

**Comment by juliohm** [comment]
Thanks @baggepinnen , will give it a try again and let you know how did it go.

**Comment by juliohm** [comment]
@baggepinnen I ended up changing my solution strategy in the problem that I am solving and won't need basis expansions at the moment. I will close the issue, but if I find myself stuck again, I will let you know.

Thank you for your prompt replies.
